server:
  port: 7001
mysql:
  url: [mysql数据库链接]
  username: [mysql用户名]
  password: [mysql密码]
  driverClassName: com.mysql.jdbc.Driver
logic:
  variable: "yaml variable 123"
mychain:
  rest:
    bizid: a00e36c5
    cipher-suit: ec
    rest-url: https://rest.baas.alipay.com
    access-id: [蚂蚁链accessid]
    access-secret: access.key
    default-account: [蚂蚁链创建的账户名]
    default-account-key: user.key
    default-account-pwd: [蚂蚁链账户密码]
    tenantid: CUALFHGC
    read-file-from-ext: false
    account: [蚂蚁链账户名]
    kmsId: [kmsId]
